if __name__ == '__main__' and __package__ is None:
    from os import sys, path
    sys.path.append(path.dirname(path.dirname(path.abspath(__file__))))

atl_museum = 'A building in Grant Park (named for a New England born Confederate colonel, not the U.S. president) houses a huge circular painting depicting the 1864 Battle of Atlanta, during which 90 percent of the city was destroyed. A team of expert European panorama artists completed the painting in Milwaukee, Wisconsin, in 1887; it was donated to the city of Atlanta in 1897.'
atl_garden = 'Occupying 30 acres inside Piedmont Park, the grounds contain acres of display gardens, including a 2-acre interactive children\'s garden; a hardwood forest with walking trails; the Fuqua Conservatory, which has unusual flora from tropical and desert climates; and the award-winning Fuqua Orchid Center. Check out the view from the Canopy Walk, a 600-foot suspension bridge through Storza Woods. A variety of special exhibits take place throughout the year.'
atl_bacchanalia = 'Often called the city\'s best restaurant, Bacchanalia has been a destination since it opened in Buckhead in 1993. The current Westside location, a renovated warehouse with 20-foot ceilings, is decorated in deep, inviting tones. The kitchen focuses on locally grown organic produce and seasonal ingredients. Items on the prix-fixe menu change frequently, but could include crab fritters, wood-grilled prime NY strip, and warm chocolate cake.'
atl_park = 'This 21-acre swath of green was the central venue for the 1996 Summer Olympics. The benches at the Fountain of Rings allow you to enjoy the water and music spectacle - four times a day, tunes are timed to coincide with water displays that shoot sprays 15 feet to 30 feet high. The All Children\'s Playground is designed to be accessible to kids with disabilities. Nearby is the world\'s largest aquarium and Imagine It! Children\'s Museum. '
pk_city = 'The Forbidden City was the Chinese imperial palace from the Ming dynasty to the end of the Qing dynasty, the years 1420 to 1912. It is located in the centre of Beijing, China, and now houses the Palace Museum. It served as the home of emperors and their households as well as the ceremonial and political centre of Chinese government for almost 500 years'

atl_museum_review = 'This turned out to be a great experience. Not what I expected and very affordable at about 8 bucks. The medium used to portray the history was a great alternative to the iMax style shows we get at other museums. You will not get this experience elsewhere. And right next to another great venue (zoo). Well worth it.'
atl_garden_review = 'Even if you don\'t think you\'re into the "Botanical" scene, I\'d recommend you check it out.  It is beautiful and a great way to spend time and get a little exercise walking around.  Why not get a few drinks and then go cruise the Botanical Garden with your date?  It is a little spendy but there are a lot worse ways to spend 20 bucks.  Worth a visit if you\'re in the area looking for something to do.'
atl_bacchanalia_review = 'The Bacchanalia is an uncommon dining experience. It\'s hidden in the back of Star Provisions, it\'s intimate, and you have the option of doing a five course meal or you can go piecemeal if you want. Another enjoyable element of the dining experience is that they bring you little experimental things the chef is whipping up for fun that aren\'t on the menu. There\'s no question that it\'s expensive, and the quality of the food doesn\'t really merit it, but if you\'re looking for somewhere special keep this place on your radar. Literally the most important thing you need to know: they have THE BEST fresh, homemade, ginger beer anywhere in this city HANDS DOWN. Get it, it\'s no joke.'
atl_park_review = 'Centennial Olympic park is a huge recreational area which was built commemorating \'96 Olympics held at Atlanta. you can freely enjoy your free time with your loved ones for free of charge. and there is a magnificent water park so if you have any kids they would of course love to visit it. There are many events hosted at the park all over the year. so you better check their schedule before you visit there.'
pk_city_review = 'The Forbidden City, the culmination of the two-thousand-year development of classical Chinese and East Asian architecture, has been influential in the subsequent development of Chinese architecture, as well as providing inspiration for many artistic works. Some specific examples include: Depiction in art, film, literature and popular culture and Live Performance concert venue'
