if __name__ == '__main__' and __package__ is None:
    from os import sys, path
    sys.path.append(path.dirname(path.dirname(path.abspath(__file__))))
"""Some real life data"""
atl_museum = 'A building in Grant Park (named for a New England born Confederate colonel, not the U.S. president) houses a huge circular painting depicting the 1864 Battle of Atlanta, during which 90 percent of the city was destroyed. A team of expert European panorama artists completed the painting in Milwaukee, Wisconsin, in 1887; it was donated to the city of Atlanta in 1897.'
atl_garden = 'Occupying 30 acres inside Piedmont Park, the grounds contain acres of display gardens, including a 2-acre interactive children\'s garden; a hardwood forest with walking trails; the Fuqua Conservatory, which has unusual flora from tropical and desert climates; and the award-winning Fuqua Orchid Center. Check out the view from the Canopy Walk, a 600-foot suspension bridge through Storza Woods. A variety of special exhibits take place throughout the year.'
atl_bacchanalia = 'Often called the city\'s best restaurant, Bacchanalia has been a destination since it opened in Buckhead in 1993. The current Westside location, a renovated warehouse with 20-foot ceilings, is decorated in deep, inviting tones. The kitchen focuses on locally grown organic produce and seasonal ingredients. Items on the prix-fixe menu change frequently, but could include crab fritters, wood-grilled prime NY strip, and warm chocolate cake.'
atl_park = 'This 21-acre swath of green was the central venue for the 1996 Summer Olympics. The benches at the Fountain of Rings allow you to enjoy the water and music spectacle - four times a day, tunes are timed to coincide with water displays that shoot sprays 15 feet to 30 feet high. The All Children\'s Playground is designed to be accessible to kids with disabilities. Nearby is the world\'s largest aquarium and Imagine It! Children\'s Museum. '
pk_city = 'The Forbidden City was the Chinese imperial palace from the Ming dynasty to the end of the Qing dynasty, the years 1420 to 1912. It is located in the centre of Beijing, China, and now houses the Palace Museum. It served as the home of emperors and their households as well as the ceremonial and political centre of Chinese government for almost 500 years'

atl_museum_review1 = 'This turned out to be a great experience. Not what I expected and very affordable at about 8 bucks. The medium used to portray the history was a great alternative to the iMax style shows we get at other museums. You will not get this experience elsewhere. And right next to another great venue (zoo). Well worth it.'
atl_museum_review2 = 'The Cyclorama is definitely worth seeing, it is an important part of our national history, however the lack of funding of for the site was readily apparent. The museum seemed to be ran by 21 year old kids either in or just out of college. The young man who narrated our tour was certainly entertaining, but not as knowledgeable as I would have liked.'
atl_museum_review3 = 'This is one of the better museums I have been too. It was well worth the $8.  Very innovative way to set up a museum and does not waste a lot of time.  Amazing job in setting up the painting with the foreground. I you have an hour or so, visit.'

atl_garden_review1 = 'Even if you don\'t think you\'re into the "Botanical" scene, I\'d recommend you check it out.  It is beautiful and a great way to spend time and get a little exercise walking around.  Why not get a few drinks and then go cruise the Botanical Garden with your date?  It is a little spendy but there are a lot worse ways to spend 20 bucks.  Worth a visit if you\'re in the area looking for something to do.'
atl_garden_review2 = 'I went there for the Chihuly Exhibit and it was terrific!  The grounds are well kept and they even have an area for children.  They have a few cafes for light eating and a main restaurant which I didn\'t try.  They were already set up for the display of the Christmas lights, so I will definitely being going back for that.'
atl_garden_review3 = 'We went for the Chihuly glass. It was impressive as was the entire place. We will be going back again. I gave it 4 stars because parking is lacking. We had to park in a residential neighborhood and walk almost a mile just to get to the entrance.'
atl_garden_review4 = 'I love this garden.. the grounds are well maintained and it is gorgeous to stroll through at night. I\'ve come for chihuly nights and for the Christmas lights. Both times were lovely. Bars located throughout the garden make it a great event to do with friends or a nice date night with a loved one.'


atl_bacchanalia_review1 = 'The Bacchanalia is an uncommon dining experience. It\'s hidden in the back of Star Provisions, it\'s intimate, and you have the option of doing a five course meal or you can go piecemeal if you want. Another enjoyable element of the dining experience is that they bring you little experimental things the chef is whipping up for fun that aren\'t on the menu. There\'s no question that it\'s expensive, and the quality of the food doesn\'t really merit it, but if you\'re looking for somewhere special keep this place on your radar. Literally the most important thing you need to know: they have THE BEST fresh, homemade, ginger beer anywhere in this city HANDS DOWN. Get it, it\'s no joke.'
atl_bacchanalia_review2 = 'Had a fantastic meal here. Great food with lots of different options for each course. Upscale, but not stuffy. Hip and sleek/modern space with a great bar area. The server was very good and helped make it a great overall experience. Located in a cool area with a food/cooking store at the front of the restaurant. EXCELLENT food and flavors, great wine list and drinks. 5 Stars for a good reason. AAA gave this restaurant four Diamonds and it has stayed on the list since 1999. Amazing.'
atl_bacchanalia_review3 = 'This is my favorite restaurant in Atlanta!! The tasting menu is amazing. The food is art and the chef combines flavors that you\'d never think would go together, but they do and they are heaven!!  It\'s a bit pricey...$$$$'
atl_bacchanalia_review4 = 'Amazing flavor combinations in a relaxed atmosphere. I can\'t say enough about how delicious our dining experience was. The portions were spot on and the several little treats from kitchen were a welcome surprise every time. This experience was worth every penny and more. Thank you for a wonderful meal.'
atl_bacchanalia_review5 = 'Google told me this resaurant costs $$..............False, very false. I went on a first date here and felt like an idiot when I walked in and my date (who obviously got the memo) was wearing a very elegant dress. I thought this was an upscale bar taco. $$ Google??? More like $$$$. In fact, I read a review of most expensive restaurants in ATL and this was #1.'
atl_bacchanalia_review6 = 'My first time here and had a lovely experience! A group of colleagues and I dined here. Having made reservations in advance dining times were sparse. When we arrived, we were asked to wait a couple minutes. We sat in their waiting area, which was very appealing, the staff was well-dressed and very friendly. Not long after we were seated. Being greeted by several service staff and explained the entire menu. I ordered 1. kumamoto oysters 2. atlantic diver scallops 3. chilled maine lobster 4. blue cheese 5. angel food cake'
atl_bacchanalia_review7 = 'Locally sourced ingredients paired with perfect techniques makes this restaurant one of the best in Atlanta but in the world. You can spot celebrities while experiencing course after course of delicious food and cleverly crafted beverages. Make your reservations in advanced there is always a full house.'
atl_bacchanalia_review8 = 'So called upscale restaurant is not really upscale. Food was okay. I wasn\'t impressed with the crowded seating arrangement and food quality. Not so great place for a date. Too much pricey compare to quality. For two people average dinner is about $230 without tip or tax. '
atl_bacchanalia_review9 = 'Quite possibly the nicest place to eat in Atlanta. The seasonal menu is always amazing. The service is impeccable. The atmosphere is romantic. '

atl_park_review1 = 'Centennial Olympic park is a huge recreational area which was built commemorating \'96 Olympics held at Atlanta. you can freely enjoy your free time with your loved ones for free of charge. and there is a magnificent water park so if you have any kids they would of course love to visit it. There are many events hosted at the park all over the year. so you better check their schedule before you visit there.'
atl_park_review2 = 'If you\'re vacationing in Atlanta there\'s a good chance you\'ll end up here, just because it houses some of the best attractions that Atlanta has to offer. It\'s a great park that connects many different sites you\'ll want to visit.'
atl_park_review3 = 'I especially love the park at night! It\'s extremely well lit and safe. Because the Zone 5 police station is mere feet from the park it is very well policed. In the middle of downtown, by night it has amazing views of the skylines by night. Kids (and a fair number of adults) love playing in The Fountain of Rings, plenty of open spaces for sports or picnicking, interesting statuary around the periphery. Two playgrounds at the north end, located right next to the CNN, the College Football Hall of Fame, Georgia Aquarium, and World of Coke. '
atl_park_review4 = 'Great internationally recognized park. Centennial Olympic is only a three minute walk from where I reside so we go often to get some fresh air & the occasional ice cream float from Googie Burger which is in the center of park next to the Fountain of Rings. My girlfriend loves the park for the various routes throughout & the several shoppes & eateries surrounding it. My favorite is the history of the \'96 Olympic athletes that\'s dispersed across the park. Perfect for everyone of all ages & nationalities.'
atl_park_review5 = 'Beautiful Park. A visual success with exquisite water features. Going on a Wednesday afternoon was a fun accident as we got to enjoy the concert in the park. I watched mesmerised as they cued the Olympic water feature perfectly to the music. The beautiful weather didn\'t work either. '

pk_city_review1 = 'Worth the visit. Get your tickets early in the day. They now limit the number of visitors.  Neat seeing where the emperor lived with his big family. His power is manifested in the palaces and living quarters.'
pk_city_review2 = 'The Forbidden City, the culmination of the two-thousand-year development of classical Chinese and East Asian architecture, has been influential in the subsequent development of Chinese architecture, as well as providing inspiration for many artistic works. Some specific examples include: Depiction in art, film, literature and popular culture and Live Performance concert venue'
pk_city_review3 = 'So busy, so impressive, a must do. One of the grandest and most ornate settings in China, right in the centre of the city. Make sure you pay the little extra and get the audio tour and take plenty of fluids on a hot day - it can get very hot. You will be a!Alex at the number of Chinese tourists, and those who want to take photos of western visitors.'
pk_city_review4 = 'One of the must visit in Beijing. The building are magnificent. You\'ll get the feeling on how the luxury was in old Chinese era. '
pk_city_review5 = 'As most of the interest things to see in China, it is enormous and nice to see. It requires you time to spend going around. There are many places inside to explore and if you close your eyes there, you can even imagine and think how the emperors lived there. Have also a look at the paintings from students in some of the shops inside, you can get a nice chinese painting in a good price. I got one with two lovely pandas :)'
pk_city_review6 = 'Walk into the history. It\'s a huge palace that you must wear your best sport shoes and take a bottle of water with you. Also, you pay 20 RMB at the entrance for a device that will guide you through each place in the palace.'

guide_review1 = 'Professional, energetic, knowledgeable, adaptive, charming, and a good conversationalist. She casually discovered what kind of people we are and continually tailored the experience to our preferences with little prompting. She went along with our request and effortlessly climbed the Arc de Triomphe and Eiffel Tower. She\'s so good and well-rounded!'
guide_review2 = 'She was very knowledgeable, personable, and very professional. She was very well prepared for just about any question and she explained everything in a very easy to understand manner. She treated us as though we were family. She helped us negotiate the metro and showed us this place that we would not have seen without her experience and thoughtfulness. Thank you!'
guide_review3 = 'She was exceptionally knowledgeable, spoke English incredibly well and was nice. We loved her. She even protected us from a would-be pickpocket pair by stepping between them and us and letting them know we were off limits. I highly recommend her.'
guide_review4 = 'We were with her for 2 days and found her to be energetic, personable, and extremely knowledgeable - especially in art history! She often used her tablet for further explanation of art or history and was well organized to answer our questions. She was punctual and arranged for an excellent driver to allow us to see more sites. Awesome guide!'
guide_review5 = ' am very happy I booked a tour with her. She is knowledgeable about the history of the city, loves her job, and communicates well. She even had some Napoleonic pictures prepared on her tablet that she shared with me. I definitely recommend her for anyone visiting this place.'